services:
  - type: web
    name: vast-scanner
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python -c "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all(); print('DB created')"
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///vast.db
      - key: GROQ_API_KEY
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
