from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

class PDFReportGenerator:
    def __init__(self, output_path):
        self.output_path = output_path
        self.styles = getSampleStyleSheet()
    
    def generate_vulnerability_report(self, project_data, scan_results, user_info, findings_details=None, ai_data=None):
        doc = SimpleDocTemplate(
            self.output_path,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        story = []
        
        # Title
        title_style = ParagraphStyle('CustomTitle', parent=self.styles['Heading1'], fontSize=24, spaceAfter=30, alignment=1)
        story.append(Paragraph("VAST Security Scan Report", title_style))
        story.append(Spacer(1, 10))
        
        # Report Header
        story.append(Paragraph(f"<b>Report Date:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", self.styles["Normal"]))
        story.append(Paragraph(f"<b>Project:</b> {project_data.get('project_name', 'Unknown')}", self.styles["Normal"]))
        story.append(Paragraph(f"<b>Analyzed By:</b> {user_info.get('username', 'Unknown')} ({user_info.get('email', 'Unknown')})", self.styles["Normal"]))
        story.append(Spacer(1, 20))
        
        # Executive Summary
        story.append(Paragraph("<b>Executive Summary</b>", self.styles["Heading2"]))
        total = sum(scan_results.values()) if scan_results else 0
        critical = scan_results.get('critical', 0)
        high = scan_results.get('high', 0)
        
        if total == 0:
            summary_text = "✅ No security vulnerabilities were found in the analyzed code."
        else:
            summary_text = f"🔴 Found {total} security issues: {critical} Critical, {high} High, {scan_results.get('medium', 0)} Medium, {scan_results.get('low', 0)} Low"
        story.append(Paragraph(summary_text, self.styles["Normal"]))
        story.append(Spacer(1, 20))
        
        # Vulnerability Statistics Table
        story.append(Paragraph("<b>Vulnerability Statistics</b>", self.styles["Heading2"]))
        stats_data = [
            ['Severity', 'Count', 'Risk Level'],
            ['🔴 Critical', str(scan_results.get('critical', 0)), 'Extreme'],
            ['🟠 High', str(scan_results.get('high', 0)), 'High'],
            ['🟡 Medium', str(scan_results.get('medium', 0)), 'Medium'],
            ['🟢 Low', str(scan_results.get('low', 0)), 'Low'],
           
            ['Total', f"{total}", '']
        ]
        stats_table = Table(stats_data, colWidths=[2*inch, 1*inch, 1.5*inch])
        stats_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a237e')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 11),
            ('BOTTOMPADDING', (0,0), (-1,0), 12),
            ('GRID', (0,0), (-1,-1), 1, colors.black),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.whitesmoke, colors.lightgrey])
        ]))
        story.append(stats_table)
        story.append(Spacer(1, 30))
        
        # AI-Powered Analysis
        if ai_data and ai_data.get('findings'):
            story.append(Paragraph("<b>🤖 AI-Powered Vulnerability Analysis</b>", self.styles["Heading2"]))
            story.append(Paragraph("<i>Expert recommendations generated by AI security assistant</i>", self.styles["Normal"]))
            story.append(Spacer(1, 10))
            
            for f in ai_data.get('findings', []):
                priority = f.get('priority', 'Info').lower()
                color = colors.red if priority == 'critical' else colors.orange if priority == 'high' else colors.yellow
                
                story.append(Paragraph(f"<b>Finding #{f.get('id', 0)+1}</b>", self.styles["Heading3"]))
                story.append(Paragraph(f"<b>CVSS Score:</b> {f.get('cvss_score', 'N/A')} | <b>Priority:</b> <font color='{color}'>{f.get('priority', 'N/A')}</font>", self.styles["Normal"]))
                story.append(Paragraph(f"<b>💡 Remediation:</b> {f.get('remediation', 'N/A')}", self.styles["Normal"]))
                story.append(Paragraph(f"<b>🎯 Exploitability:</b> {f.get('exploitability', 'N/A')}", self.styles["Normal"]))
                story.append(Spacer(1, 10))
        
        # All Detailed Findings
        if findings_details:
            story.append(Paragraph("<b>🔍 All Detected Vulnerabilities</b>", self.styles["Heading2"]))
            story.append(Spacer(1, 10))
            
            for i, f in enumerate(findings_details, 1):
                severity = f.get('severity', 'info')
                color_map = {'critical': colors.red, 'high': colors.orange, 'medium': colors.yellow, 'low': colors.green, 'info': colors.blue}
                color = color_map.get(severity, colors.grey)
                
                story.append(Paragraph(f"{i}. <b>[{severity.upper()}]</b> {f.get('message', 'No message')}", self.styles["Normal"]))
                story.append(Paragraph(f"   <b>Line:</b> {f.get('line', 'Unknown')} | <b>Tool:</b> {f.get('tool', 'Unknown')}", self.styles["Normal"]))
                if f.get('code_snippet'):
                    story.append(Paragraph(f"   <b>Code:</b> <i>{f.get('code_snippet', '')[:100]}</i>", self.styles["Normal"]))
                story.append(Spacer(1, 5))
        
        # Footer
        story.append(Spacer(1, 40))
        story.append(Paragraph("<i>Generated by VAST - Vulnerability Analysis Security Tool</i>", self.styles["Italic"]))
        story.append(Paragraph(f"<i>Report ID: VAST-{datetime.now().strftime('%Y%m%d%H%M%S')}</i>", self.styles["Italic"]))
        
        doc.build(story)
        return self.output_path
